name: Ccru
favicon: null
layout_spectrum: 1
title: 'http://ccru.net/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080908'
    - '#333431'
    - '#5c5b5c'
    - '#d8dea2'
    - '#7fc047'
  brandStrength: 0.1875
  lightness: 0.25
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose:
  - name: awareness
    item: null
    url: null
